### ISSUE TITLE
T1.1: Project and financial management

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#14]
- **WP1:** [Project Management](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP1)
- **Lead Institution:** Université Paris-Sud
- **Partners:** Logilab, Université de Versailles Saint-Quentin, Université Joseph Fourier, CNRS, University of Oxford, University of Sheffield, University of Southampton, University of St Andrews, University of Warwick, Jacobs University Bremen, University of Kaiserslautern, University of Silesia, Universität Zürich, Simula Research Laboratory
- **Work phases:** 0-48!.2,0-3,10-12,22-24,34-36,42-48
- **Deliverables:** D1.1 (#17); D1.2 (#18), D1.6 (#22)
- **Proposal:** [p. 34](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)

This task includes the following activities:
- [x] Preparation and Distribution of the Consortium Agreement; follow up: #193;
- [x] Setting up the project website, intranet and communication procedures for effective communication: D1.1 (#17), #173;
- [ ] Organisation of project review and progress meetings: #156, #223;
- [ ] Establishment and maintenance of external contacts (with the EC, other relevant national / EU projects, other academic and industrial stakeholders) to organise transfer of knowledge, present and promote project results: #158, #167, #202, #205, ...;
- [ ] Progress and Financial Reporting to the EC: #221;
- [ ] Data and IPR Management will be managed in accordance with agreed rules stated in the Consortium Agreement and in accordance with the Data Management Plans D1.2 (#18), D1.6 (#22).
