### ISSUE TITLE
Second grant agreement amendment

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#193]
- [x] Addition of FAU Erlangen-Nürnberg
  - [x] new site description
  - [x]  Redistribute Fundings and Person-Months between Bremen and FAU (agreement between Bremen and FA admins)
  - [x]  Redistribute tasks, and leaderships to FAU 
  - [x] update all the issues to the new responsibilities

- [x] Modify PhD position into postdoc position at UPSud
- [x] Change UJF name into Université Grenoble Alpes
- [x] Modify Person-Months repartition within CNRS/Bordeaux
- [x] Change due date for deliverables [D4.7](https://github.com/OpenDreamKit/OpenDreamKit/issues/96) (M14 to M24), [D4.3](https://github.com/OpenDreamKit/OpenDreamKit/issues/92) (M12 to M18) and [D5.4](https://github.com/OpenDreamKit/OpenDreamKit/issues/117) (M12 to M18)
- [x] **TODO**: what to do with [D4.1](https://github.com/OpenDreamKit/OpenDreamKit/issues/83) (due M6 but will be delivered only M18)
- [x] Remove or replace D6.8 (#142, #201) See also [here](https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2017-01-19-EdinburghSteeringCommittee/ProgressReports/JacU.md) for two other deliverables change

- [x] Change lead + PM allocation for Simula
- [x] Change lead of USFD (+ person-months?)

- [x] Bremen stays part of the Project until (at least Fall 2017 when MK's adjunct professorship and Florian Rabe's temporary employment ends) with @florian-rabe as the local representative (he is already a PI at JacU).  
- [x]  Vote on the new grant agreement -> SC meeting in Edinburgh (2017)
  cc: @bpilorget @nthiery @videlec @ClementPernet @martinal @mikecroucher 

The above items have been voted upon at Edinburgh's [Steering Committee Meeting](http://opendreamkit.org/meetings/2017-01-19-EdinburghSteeringCommittee/steering-minutes/)

- [x] Fix title for #21: should be Internal Progress Report for year **3**

- [x] Update the EU portal for all relevant items above

- [X] Add XFEL partner for the move of H. Fangohr and his team

- [X] Add a termination date for Southampton partner

**Comment by kohlhase** [comment]
I have started working on the grant agreement amendment, first changes are pushed.

**Comment by kohlhase** [comment]
@bpilorget @nthiery If I am forgetting something above, please extend the task list.

**Comment by kohlhase** [comment]
It turns out that I have to sort out on personell problem first, before I can make full progress here. This will take one to two more weeks (admin).

**Comment by bpilorget** [comment]
Hello @kohlhase and @nthiery . I am back again in the game. What is the current situation of the amendment? Is it clear what we want to do with the Bremen site? That piece of information would clarify the Resources situation.
I have warned the UPSud administration. Once everything is clear we can start the process

**Comment by kohlhase** [comment]
> am back again in the game.

very  good to hear that, the amendment is done from my side, and I had asked Nicolas and you to proof-read from the admin side. 

I would like to make progress on this, so that I can hire my people in Erlangen for the next year (otherwise I have to leave more months in Bremen), which would be less than ideal, since that misdirects my overhead.

**Comment by bpilorget** [comment]
@nthiery @kohlhase 
OK I began to look it around. I need to go through the updated PDF version of the proposal file to be able to read everything easily (to check id deliverables leads were correctly changed etc). 
I saw you wrote the site description and also moved some resources to Nürnberg. 

I have two remarks:
1) Resources tables seem wrong for FAU and Bremen. Adding all cost lines, it should be respectively 69600€ and 6300€ (not 64600€ and 11300€). 
2) Apparently you wish to keep Maeder and Iancu in Bremen for 12 PM in Bremen and then move them for 12 other PM in FAU. Minor question is when would they change institution? Major question is one of them needs to become PI of that partner I think.

Eugenia Shadlova will come back in the office on the 7th November. If we can calrify the max of this before she comes abck that would be nice. She could then do the admin changes with Bremen and FAU (I guess FAU is already up to be part of the project?).

**Comment by bpilorget** [comment]
@martinal @minrk We should change the PI of Simula. this means adding a CV in the proposal and reallocatiing Hans-Peter's person-months. Is Martin taking the lead officially?

**Comment by martinal** [comment]
@bpilorget yes. What do I need to do?

**Comment by bpilorget** [comment]
@martinal You should add your CV in the repository (OpenDreamKit\Proposal\CVs), replace Hans-Peter's CV with yours in the Proposal and also change the resources allocation (OpenDreamKit\Proposal\resources) to include the PM change in the small paragraph concerning Simula.

**Comment by bpilorget** [comment]
@mikecroucher Please Mike, when you will have talked with Lucy Moffat from Sheffield, please do the following changes in the Proposal: in the OpenDreamKit\Proposal\resources docuemnt, modify the paragraph about Sheffield to add yourself as PI and do the PM change

**Comment by pdehaye** [comment]
@nthiery  @bpilorget @kohlhase Shouldn't the second-to-last point concerning Bremen and @florian-rabe be presented differently? (judging from Steering Committee slides I have peeked at ahead of time)

**Comment by florian-rabe** [comment]
Regarding Paul's questions:
I will remain in Bremen in the immediate future (with at this point undecided long-term status).
The current plan is to retain Bremen as a site with me as the only person.

So, indeed, the wording of the second-to-last point is a bit misleading (presumably because it was written at a point when my future was even less predictable).

**Comment by pdehaye** [comment]
Thanks @florian-rabe for the response. I have edited the line accordingly.

**Comment by bpilorget** [comment]
Amendmznt was submitted today

**Comment by kohlhase** [comment]
wonderful, when are we expecting it to become effective?

**Comment by kohlhase** [comment]
Because once it does, we need to augment the web site (e.g. the FAU logo and that of Hans' new affiliation need to be added).

**Comment by bpilorget** [comment]
The Project Officer needs to accept. From memory it is 45 or 60 days for them to answer. But it can be much faster as they were already aware of all the changes. FYI the addition of FAU is retroactive to 1st Sept 2016 so that all your expenses since then there can be eligible.

**Comment by bpilorget** [comment]
Also at this ppint i havent added  withdrawal date for Southampton and Jacobsuni as no one can tell for now until when they will have OdK related expenses. If no amendment is required in the future they will simply become "ghost" partners

**Comment by kohlhase** [comment]
> Also at this point i havent added withdrawal date for Southampton and Jacobsuni as no one can tell for now until when they will have OdK related expenses. If no amendment is required in the future they will simply become "ghost" partners

yes, that is a good way to deal with this (at least for JacU). In particular, we do not know when/if @florian-rabe  will leave Jacobs.

**Comment by fangohr** [comment]
Yes, also good for Southampton - thank you @bpilorget for managing this so well with plenty of foresight.

**Comment by bpilorget** [comment]
All good from all sides now. New submission to be done soon. Fingers crossed.

**Comment by bpilorget** [comment]
Amendment accepted!
