### ISSUE TITLE
Resubmit deliverables according to reviewers' recommendations

### ISSUE THREAD

**Issue by bpilorget** [OpenDreamKit/OpenDreamKit#209]
## Deliverables submitted in June or before to resubmit:

- [x] D1.1: Basic Project Infrastructure #17 
- [x] D2.1: Starting press release #34 
- [x] D3.1: Virtual images and containers #58 
- [x] D4.1:  Python/Cython bindings for PARI and its integration in Sage #83
- [x] D4.2: Active/Structured Documents Requirements and existing Solutions #91 
- [x] D5.1: Turn the Python prototypes for tree exploration into production code, integrate to Sage #107 
- [x] D6.1: Full-text Search (Formulae + Keywords) over LaTeX-based Documents #133 

## Deliverables due for month 12

- [x] D1.3: Internal progress report #19 
- [x] D2.2: Community building #42 
- [x] D2.3: Review on emerging technologies #43 
- [x] D3.3: Support for the SCSCP interface protocol in the distribution of all relevant components #62 
- [x] D4.4: Basic Jupyter interface for GAP, PARI/GP, SageMath, Singular #93 
- [x] D4.5: Sage notebook / Jupyter notebook convergence #94 
- [x] D4.6: Tools for collaborating on notebooks via version-control #95 
- [x] D6.2: Initial DKS base Design #136 
- [x] D6.3: Design of Triform (DKS) Theories #137 (Due M15 but finished already)
