### ISSUE TITLE
D4.4: Basic Jupyter interface for GAP, PARI/GP, SageMath, Singular

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#93]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2016-08-31 (month 12)
- **Nature:** Other
- **Task:** T4.1 (#69)
- **Proposal:** [p.48](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.4/report-final.pdf)**

The [Jupyter Notebook](https://jupyter.org) is a web application that enables the creation and sharing of executable documents which contain live code, equations, visualizations and explanatory text. Thanks to a modular design, Jupyter can be used with any computational system that provides a so-called [_Jupyter kernel_](https://jupyter.readthedocs.io/en/latest/projects/kernels.html) implementing the [_Jupyter messaging protocol_](https://jupyter-client.readthedocs.io/en/latest/) to communicate with the notebook. OpenDreamKit therefore promotes the Jupyter notebook as user interface of choice, in particular since it is particularly suitable for building modular web based Virtual Research Environments.

This deliverable aims at ODK's main computational components all having basic Jupyter kernels implemented and distributed. Full featured Jupyter interfaces will follow up in deliverable [D4.7](https://github.com/OpenDreamKit/OpenDreamKit/issues/96). The SageMath Jupyter kernel is a foundation for [D4.5](https://github.com/OpenDreamKit/OpenDreamKit/issues/94): Sage notebook / Jupyter notebook convergence.

We have implemented basic kernels for:
- [x] GAP:
    - [x] https://github.com/gap-packages/jupyter-gap
    - [x] [pip package](https://pypi.python.org/pypi/jupyter-kernel-gap)
    - [ ] Optional SageMath package `gap_jupyter`: [trac #21416](https://trac.sagemath.org/ticket/21416)
    - [ ] SageMathCloud integration: https://github.com/sagemathinc/smc/issues/1706
    - [x] Features: TAB-completion, documentation lookup, code introspection, output history, interruption, timing, debugger
    - Upcoming features in [D4.7](https://github.com/OpenDreamKit/OpenDreamKit/issues/96): syntax highlighting (should just require installing Code Mirror's syntax file for GAP), pretty printing, 2D/3D plots, live manual.
- [x] PARI/GP:
    - [x] https://github.com/jdemeyer/pari_jupyter
    - [x] PARI patches required for plotting: `jeroen-svg` branch of http://pari.math.u-bordeaux.fr/git/pari.git
    - [x] [pip package](https://pypi.python.org/pypi/pari_jupyter)
    - [x] Optional SageMath package `pari_jupyter`: [trac #19372](https://trac.sagemath.org/ticket/19372), [#19992](https://trac.sagemath.org/ticket/19992), [#22177](https://trac.sagemath.org/ticket/22177)
    - [ ] SageMathCloud integration: https://github.com/sagemathinc/smc/issues/1709
    - [x] Features: TAB-completion, (short) documentation lookup, output history, interruption, timing, 2D plots
    - Upcoming features in [D4.7](https://github.com/OpenDreamKit/OpenDreamKit/issues/96): syntax highlighting, pretty printing, long documentation lookup, live manual?, code introspection?, debugger
- [x] Singular:
    - [x] https://github.com/sebasguts/jupyter-singular
    - [x] [pip package](https://pypi.python.org/pypi/jupyter-kernel-singular/)
    - [x] Optional SageMath package `singular_jupyter`: [trac #22378](https://trac.sagemath.org/ticket/22378)
    - [x] SageMathCloud integration: https://github.com/sagemathinc/smc/issues/1553
    - [x] Features: TAB completion, static 3D plots generated by surf, basic support for interactive widgets (IPyWidgets).
    - Upcoming features in [D4.7](https://github.com/OpenDreamKit/OpenDreamKit/issues/96): live 3D plots, ...

Meanwhile, the following Jupyter kernel has been implemented by the community, with some help of the ODK participants:
- [x] SageMath (built on top of Jupyter's Python kernel)
    - [x] see this series of [trac tickets](https://trac.sagemath.org/query?status=closed&summary=~Jupyter&col=id&col=summary&col=status&col=type&col=priority&col=milestone&col=component&order=priority)
    - [x] Part of the SageMath distribution
    - [x] SageMathCloud integration: native
    - [x] Features: TAB-completion, syntax highlighting, pretty printing, 2D/3D plots, documentation lookup, live manual, code introspection, output history, interruption, timing, debugger.
    - Interactive widgets (IPyWidgets): see [D4.5](https://github.com/OpenDreamKit/OpenDreamKit/issues/94)
  
Finally, the following kernel has been made available within SageMath:
- [x] R: see trac [#19427](https://trac.sagemath.org/ticket/19427)

**Comment by jdemeyer** [comment]
For SageMath, a basic implementation is already part of SageMath itself. Some improvements need review at:
- http://trac.sagemath.org/ticket/19128
- http://trac.sagemath.org/ticket/19132
- http://trac.sagemath.org/ticket/19135

**Comment by jdemeyer** [comment]
Basic PARI/GP Jupyter kernel: https://github.com/jdemeyer/pari_jupyter

**Comment by jdemeyer** [comment]
@embray: my first PyPI submission: https://pypi.python.org/pypi/pari_jupyter/1.1.2

**Comment by sebasguts** [comment]
I have started a basic interface to Singular here: https://github.com/sebasguts/jupyter-singular
Currently maybe an early beta. Also, one needs the following python module for the Singular bindings: https://github.com/sebasguts/SingularPython

**Comment by embray** [comment]
:+1:

**Comment by jpflori** [comment]
Hi Jeroen,

Can you report on what you plan to bind here?
Is it mainly meant to give an interface similar to Singular interpreter?
Or is it more intricate like Sage library-like (broken) interface?

Best,


2016-02-24 0:16 GMT+09:00 Erik Bray <notifications@github.com>:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDreamKit/OpenDreamKit/issues/93#issuecomment-187736167>
> .
>



-- 
Jean-Pierre Flori

**Comment by jdemeyer** [comment]
> Hi Jeroen,

Jeroen? I guess you mean Sebastian .

**Comment by jpflori** [comment]
Oh yes!
Sorry about that.
For some mysterious reason I assumed that the same person posted the two
first mails in this thread.

2016-02-24 16:15 GMT+09:00 jdemeyer <notifications@github.com>:

> Hi Jeroen,
>
> Jeroen? I guess you mean Sebastian .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDreamKit/OpenDreamKit/issues/93#issuecomment-188113618>
> .
>



-- 
Jean-Pierre Flori

**Comment by sebasguts** [comment]
No worries :).
Current plan is to have an interpreter-like interface, but with some additional features like displaying pictures in the notebook and supporting ipywidgets. What kind of features would you like to see?

**Comment by markuspf** [comment]
If the GAP Jupyter notebook is supposed to go into sagemath (cloud?), someone will have to tell me how to get it there. It's not obvious to me how that works.

**Comment by nthiery** [comment]
On Tue, Jul 26, 2016 at 08:41:24AM -0700, Markus Pfeiffer wrote:
>    If the GAP Jupyter notebook is supposed to go into sagemath (cloud?),
>    someone will have to tell me how to get it there. It's not obvious to
>    me how that works.

I guess this could boil down to something like:

- Preparing a gap package with everything needed to run the gap kernel
  (if needed)

- Preparing a Sage package. That is essentially an install shell
  script in <sage>/build/pkg/jupyter_kernel_gap/ + some metadata
  files; see:
  http://www.sagemath.org/git-developer-guide/packaging.html.

  The install script would:

  - install the gap package in the gap tree in the Sage distribution:
    <sage>/local/gap/latest
  - copy the kernel file in:
    <sage>/local/share/jupyter/kernels

- Creating a ticket to get this as optional and then standard Sage
  package.

We certainly can help for the latter parts!

Cheers,
				Nicolas

**Comment by dimpase** [comment]
My understanding that this should happen simultaneously with libGAP (a Sage package, a C-library interface to GAP kernel) being replaced with what Markus is going to provide.

**Comment by markuspf** [comment]
Thanks @nthiery.

I don't think the Jupyter Kernel is an appropriate GAP Package, since it's a program that wraps around GAP (and can't be loaded in any sensible way).
For the initial implementation as it is available now we only need to have the kernel installed for Jupyter, and make sure that the correct configuration (i.e. the GAP executable) is available.

There might be some merit in distributing this wrapper as part of GAP 4.9.

Is there any way for me to get access to a sage development system without having to install it myself? My operating system is not supported by sage (and it seems a lot of effort to get any development system to run at all).

With the prototype kernel, of course some of the requirements for contributions might be debated by the sage community.

At this point it is important that we provide a deliverable which is not just a link, and I am not sure what that means for a "Basic Jupyter Interface for GAP". The kernel has been available since the kick-off meeting in September last year, and I have worked on improving it since. 

The C library is a different beast entirely and in my mind has little to do with this deliverable at this point.

**Comment by dimpase** [comment]
What kind of OS is this? Do you mean to say there is no binary available, or that it's really unsupported, like it's something like OpenBSD or Hurd?

**Comment by dimpase** [comment]
If your box supports VMWare or VirtualBox, you can install a supported OS into it and build Sage there.

**Comment by videlec** [comment]
... or qemu, docker. You can also open an account on https://cloud.sagemath.com where you can do Sage development online (not very handy).

**Comment by slel** [comment]
To use SageMathCloud at https://cloud.sagemath.com for Sage development,
- open an account,
- create a project,
- email help@sagemath.com with the project id
  and ask them to upgrade the project for Sage development
- you can ssh into your project (after starting it from the web interface)
- a good tool is tmux (or screen) in combination with ssh
- once your project is upgraded you have network access from it,
  so you can git clone etc.

**Comment by dimpase** [comment]
By the way, it is interesting to hear that it has nothing to do with libGAP or its replacement. I believe that back in Bremen we heard something different, although I might have misunderstood this.

**Comment by markuspf** [comment]
We just published a Docker container to deploy the basic GAP/Jupyter interface here: https://github.com/gap-system/gap-docker-jupyter, I also wrote a blogpost about it there: http://opendreamkit.org/activities/2016-08-03-gap-docker-jupyter/ (btw, these activities are not very discoverable or visible on the website).

The roadmap for the next iteration of the Jupyter interface for GAP is to export an API from GAP for the purposes of using it as a library in the Jupyter kernel, and to get rid of the REPL wrapping, as its really fragile. Currently work on this is scheduled for September. We also have two project students contributing GUI elements for method selection/availability, subgroup explorer, and hopefully also an interactive Todd-Coxeter, as currently available in xgap.

I hope the CodeMirror [GAP syntax highlighting and formatting helper](https://github.com/webgap/CodeMirror) will be ready for merge sooner rather than later, too.

**Comment by jdemeyer** [comment]
> we would have as well something like "sage --gap-jupyter".

No, you just run `sage -n jupyter` and start a GAP notebook.

**Comment by jdemeyer** [comment]
> At this point it is important that we provide a deliverable which is not just a link, and I am not sure what that means for a "Basic Jupyter Interface for GAP". The kernel has been available since the kick-off meeting in September last year, and I have worked on improving it since.

I think a basic Jupyter interface means: a way to use GAP within Jupyter that actually works well enough to use in production. It doesn't need to support stuff like TAB-completion or syntax highlighting, but it should correctly run GAP commands.

The github page for https://github.com/gap-packages/jupyter-gap still has the text "Please note that this software is still in the early stages of development and names of kernels, assumptions, and architecture might change on a day-to-day basis without notice."

For me, this reads like "don't use this code yet".

**Comment by dimpase** [comment]
@jdemeyer : "No, you just run sage -n jupyter and start a GAP notebook."
do you mean "choose GAP kernel" in "Kernel" menu?

**Comment by jdemeyer** [comment]
That's one way but I really meant choose "GAP" from the "New" menu.

**Comment by bpilorget** [comment]
Is the report close to an end?

**Comment by minrk** [comment]
@nthiery Paris-Sud is the leader on this as well. Let me know if there is anything I can do to help finish this report.

**Comment by bpilorget** [comment]
The README gives info on how to write deliverables (scroll down): https://github.com/OpenDreamKit/OpenDreamKit

**Comment by nthiery** [comment]
Oops, right, PSud is lead here. Let's gets things moving, and aim for having kernels for Pari, Singular, and GAP installable in Sage as optional packages.

- @markuspf: I am working on an optional spkg for Sage which basically runs the installation instructions posted on your git repository. Would you be available at some point tomorrow Friday in case there are some technical things to polish together?
- @sebasguts: what's the status of the Singular kernel? Is it in a state where we could consider including it as an optional package for Sage? Does it requres Singular 3 or 4?

**Comment by nthiery** [comment]
@markuspf, @dimpase: oh wait, but we don't have io and json installed in Sage's gap, even with the optional gap_packages spkg. That probably explains the failure.

@dimpase: would it be meaningful / easy to add those to gap_packages?

**Comment by nthiery** [comment]
Ok, once io and json installed by hand, this seems to work smoothly. Cool :-)
So I'll write an spkg tomorrow, and then we have to decide how to "package" io and json in Sage (each in it's own spkg, in gap_packages, ...).

**Comment by nthiery** [comment]
@markuspf: within Sage, the gap command is called ... gap. Would it be sensible to set 'gap' as default value for JUPYTER_GAP_EXECUTABLE, rather than complaining that it is not defined?

**Comment by dimpase** [comment]
@nthiery : adding io properly (to GAP as well as to libGAP) is a bit tricky, as it has a GAP kernel module (although IIRC @vbraun was able to do this back in January); it looks as if json is also like this. 
On the other hand if one ignores libGAP it should not be a problem, they can be then GAP-only packages.

**Comment by jdemeyer** [comment]
> is there an spkg or pip package for the Pari Kernel?

Yes, see https://pypi.python.org/pypi/pari_jupyter

It is also an optional Sage package.

**Comment by dimpase** [comment]
anyhow, let me whether you'd like me to make a io/json@GAP package for Sage.

**Comment by markuspf** [comment]
@nthiery [this](https://github.com/gap-packages/jupyter-gap/commit/1dda8b569c7d29cd0609713dfadadc23d1cf9afe) should do what you want I guess?

**Comment by markuspf** [comment]
I noticed that I *could* make the kernel independent of `io` and `json` now, but I wasn't going to bother since I'll obviously be abandoning the REPL wrapping as it is done currently.

**Comment by jdemeyer** [comment]
@markuspf : what's your opinion on https://github.com/gap-packages/jupyter-gap/issues/26 to simplify installation?

**Comment by markuspf** [comment]
@jdemeyer If it was a pull-request I'd click merge ;)

**Comment by jdemeyer** [comment]
> @jdemeyer If it was a pull-request I'd click merge ;)

Great! I will look into this now.

**Comment by jdemeyer** [comment]
I did not manage to get the GAP kernel working. The Jupyter debug output says
```
[I 13:44:46.009 NotebookApp] Kernel started: 297b7f87-fd48-4025-9c24-86447412001a
[W 13:44:46.130 NotebookApp] 404 GET /static/components/codemirror/mode/gap/gap.js (::1) 2.14ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[IPKernelApp] ERROR | ('starting GAP: gap',)
[IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: u'comm_open'
[IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: u'comm_open'
[IPKernelApp] ERROR | (u'command JUPYTER_RunCommand("1+1; ;");',)
[IPKernelApp] ERROR | (u"reply Error, Variable: 'JUPYTER_RunCommand' must have a value\r\n",)
[IPKernelApp] ERROR | (u'json part: ',)
[IPKernelApp] ERROR | (u"rest part: Error, Variable: 'JUPYTER_RunCommand' must have a value\rError, Variable: 'JUPYTER_RunCommand' must have a value\r\n",)
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/jupyter_gap_wrapper/kernel.py", line 124, in do_execute
    jsonp = json.loads(res_json)
  File "/usr/local/src/sage-config/local/lib/python/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/src/sage-config/local/lib/python/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/src/sage-config/local/lib/python/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jdemeyer** [comment]
The kernel is correctly (I guess) executing the command
```
/usr/local/src/sage-config/local/gap/latest/bin/x86_64-unknown-linux-gnu-gcc-default64/gap -m 24m -l /usr/local/src/sage-config/local/gap/latest -n -b -T /usr/local/src/sage-config/local/lib/python2.7/site-packages/jupyter_gap_wrapper/gap/setup.g
```

Manually running this command gives
```
Error, Variable: 'IO_WrapFD' must have a value
```

And yes, I did install the `io` and `json` packages that Nicolas mentioned.

**Comment by markuspf** [comment]
This means that `io` is not loaded (which in turn probably means it wasn't loadable in `GAP`, because the Jupyter GAP glue code tries loading it). Debugging this usually involves executing the gap command manually and then `DisplayPackageLoadingLog(DEBUG_LOADING)` to find out where it went wrong.

**Comment by jdemeyer** [comment]
Hmm, that says
```
#I  io: no package with this name is installed, return 'fail'
```

I must have messed up installing the package, although I don't see what went wrong...

**Comment by jdemeyer** [comment]
Here is what I did: I unpacked the tarball of the GAP `io` package and then did
```
./configure --with-gaproot="$SAGE_LOCAL/gap/latest" --prefix="$SAGE_LOCAL"
make
make install
```

This seems to have worked without errors.

**Comment by jdemeyer** [comment]
Got it! The packages need to be manually(!) copied to the `pkg` directory inside the GAP installation.

**Comment by jdemeyer** [comment]
The GAP kernel works now...

**Comment by jdemeyer** [comment]
> we have to decide how to "package" io and json in Sage (each in it's own spkg, in gap_packages, ...).

I would say: add it to `gap_packages`.

**Comment by dimpase** [comment]
On Fri, Sep 2, 2016 at 12:32 PM, jdemeyer <notifications@github.com> wrote:

> we have to decide how to "package" io and json in Sage (each in it's own
> spkg, in gap_packages, ...).
>
> I would say: add it to gap_packages.
>
if it works with libGAP I'll do this. Else I'd create another separate spkg.

**Comment by jdemeyer** [comment]
It seems that installing the packages `io` and `json` break libGAP in Sage:
```
**********************************************************************                                                                                                  
File "src/sage/libs/gap/libgap.pyx", line 11, in sage.libs.gap.libgap                                                                                                   
Failed example:                                                                                                                                                         
    a = libgap(10)
Expected nothing
Got:
    An error occurred, but libGAP has no handler set.
    Error message: Error, no support for dynamic loading
    <BLANKLINE>
    An error occurred, but libGAP has no handler set.
    Error message: Error, no support for dynamic loading
    <BLANKLINE>
    An error occurred, but libGAP has no handler set.
    Error message: Error, no support for dynamic loading
    <BLANKLINE>
    An error occurred, but libGAP has no handler set.
    Error message: Error, no support for dynamic loading
    <BLANKLINE>
**********************************************************************
File "src/sage/libs/gap/libgap.pyx", line 49, in sage.libs.gap.libgap
Failed example:
    libgap.eval('5/3 + 7*E(3)').sage()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 498, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 861, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.gap.libgap[11]>", line 1, in <module>
        libgap.eval('5/3 + 7*E(3)').sage()
      File "sage/libs/gap/element.pyx", line 1476, in sage.libs.gap.element.GapElement_Cyclotomic.sage (build/cythonized/sage/libs/gap/element.c:13213)
        coeff = self.CoeffsCyc(conductor).sage()
      File "sage/libs/gap/element.pyx", line 2165, in sage.libs.gap.element.GapElement_MethodProxy.__call__ (build/cythonized/sage/libs/gap/element.c:16823)
        return GapElement_Function.__call__(self, * ([self.first_argument] + list(args)))
      File "sage/libs/gap/element.pyx", line 2051, in sage.libs.gap.element.GapElement_Function.__call__ (build/cythonized/sage/libs/gap/element.c:16294)
        raise ValueError('libGAP: ' + str(msg))
    ValueError: libGAP: Error, CoeffsCyc: function is not yet defined

**********************************************************************
```
and many more failures. All these failures went away after removing the `io` and `json` packages.

**Comment by dimpase** [comment]
@jdemeyer : oh, this is bad news; still, we can disable autoloading of io and json, then everything would function well as long as they are not loaded. Add file named `NOAUTO` in `gap-<...>/pkg/` with names of packages not to be autoloaded; e.g. to disable IO put there line 

    IO

this would do as a workaround while we update libGAP...

**Comment by markuspf** [comment]
I just released a new version of the jupyter wrapper that does not depend on `io`, but still depends on `json`, sorry. (really, a sufficiently inclined person could write a json printer/reader in GAP and that would make json go away as well. I am not quite inclined enough right now).

**Comment by jdemeyer** [comment]
Just curious why you need JSON...

My PARI wrapper kernel certainly does not need it, nor does the bash kernel. Why do you need it for GAP?

**Comment by markuspf** [comment]
IIRC, I wrap relevant output in JSON, and do side-channel messaging to display graphs etc.

I had very low motivation looking at this right now, because the new kernel based on something that looks not quite unlike libgap is basically around the corner anyway.

In any case, I made the JSON printing work without JSON and will commit that later today too...

**Comment by nthiery** [comment]
@markuspf: within Sage, the gap command is called ... gap. Would it be sensible to set 'gap' as default value for JUPYTER_GAP_EXECUTABLE, rather than complaining that it is not defined?
Jeroen: how did you handle this? Setting this variable in Sage's scripts?

**Comment by nthiery** [comment]
Strange, io seems to not break Sage for me:

    sage: libgap.LoadPackage("io")
    true
    sage: libgap(10+10)
    20
    sage: a = libgap(10)
    sage: a + 10
    20

**Comment by nthiery** [comment]
Thanks guys for all the progress today while I got distracted looking over the other deliverables!
The plan is to make gap_kernel into a pip package, and have an essentially trivial spkg on top of it, right?

**Comment by jdemeyer** [comment]
> Jeroen: how did you handle this? Setting this variable in Sage's scripts?

Markus listened to you and he already fixed this issue.

**Comment by dimpase** [comment]
@nthiery : libGAP behaviour depends upon GAP workspace used. 
To reproduce, run

     ./sage -tp src/sage/libs/gap/libgap.pyx

2 or more times (the 1st run might be OK, as the workspace still does not have IO loaded, the 2nd run for me always produces errors). Then you will need to update your GAP workspace to have functioning libGAP.

**Comment by markuspf** [comment]
https://github.com/gap-packages/jupyter-gap/pull/29 works without `json` or `io`, as far as I can tell at the moment. It's ugly though.

**Comment by jdemeyer** [comment]
I created https://trac.sagemath.org/ticket/21416 to add a Sage package for the GAP kernel.

**Comment by sebasguts** [comment]
On the status of the Singular Kernel:

Current version is available at https://github.com/sebasguts/jupyter-singular

Currently, there is a beta version, depending on the ipykernel. It communicates with Singular using libSingular, and a python wrapper for the Singular command line, available at https://github.com/sebasguts/SingularPython
Current features of the kernel are, besides of stable wrapping:
* Tab completion.
* Displaying images created by surf inside the notebook.
* Some basic support for IPyWidgets

For an example, see
https://github.com/sebasguts/jupyter-singular/blob/master/Demo.ipynb

Currently, we are working on some better support for the surf images, specially having real 3d models of the surfaces, which can be turned around live.
To achieve that, and to take load from the server, we have tested some js versions of surf, both with webgl and without, and currently this seems not to be feasible, due to limitations in webgl (no 64bit floats) and the speed of js.

**Comment by dimpase** [comment]
perhaps instead of surf you can try jmol and/or jsmol? While it's not ideal, it does work, it's used in Sagemath as the default 3D viewer.

**Comment by jdemeyer** [comment]
> It communicates with Singular using libSingular, and a python wrapper for the Singular command line

Can you clarify the "and"? Why does it need two different ways to communicate to Singular?

**Comment by sebasguts** [comment]
Actually, the python wrapper is on top of it.

The python module SingularPython accesses the Singular parser through libSingular. So this module wraps the C commands to do this in python.

**Comment by slel** [comment]
For visibility, would kernel developers/ maintainers add them to the wiki page
listing existing Jupyter kernels?
I would do it but I would not know how to fill in the "dependencies" column.
https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages

**Comment by markuspf** [comment]
My student made a codemirror mode, I think he's trying to figure out how it should be distributed (via npm I guess).

**Comment by nthiery** [comment]
I will start shortly writing the report for this deliverable. @sebasguts, @markuspf, @jdemeyer, could you prepare a screenshots demonstrating the kernel and some of its features, for Singular, GAP,  and Pari respectively? @jdemeyer: in case you could do one for Sage, that would be welcome.

**Comment by nthiery** [comment]
Additional instructions: put the screenshots as screenshot-<component>.png files in https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4/D4.5. Also save the corresponding notebook as demo-<component>.ipynb there, or add a link from the description of this issue if you have this demo already hosted somewhere (like for @sebasguts Demo.ipynb).
Thanks!

**Comment by nthiery** [comment]
@sebasguts, @markuspf, @jdemeyer: ping for the screenshots!

**Comment by nthiery** [comment]
Besides, we are missing pip/Sage packages for GAP, Pari (just the pip one) and Singular. Anyone has time to make progress on them? Once the pip package is done, the work for the Sage one is essentially trivial; I could possibly handle it.

**Comment by sebasguts** [comment]
@nthiery: I just pushed a screenshot. I will try to do the pip packages soon.

**Comment by jdemeyer** [comment]
@nthiery: There is a pip package for `pari_jupyter` (it is even linked from the issue description at the top)

I will have a look at screenshot and demo.

**Comment by jdemeyer** [comment]
> Additional instructions: put the screenshots as screenshot-<component>.png files in https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4/D4.4. Also save the corresponding notebook as demo-<component>.ipynb there

Done for PARI.

**Comment by nthiery** [comment]
On Tue, Sep 20, 2016 at 04:29:58AM -0700, jdemeyer wrote:
>    [1]@nthiery: There is a pip package for pari_jupyter (it is even linked
>    from the issue description at the top)

Yes, sorry, I just meant GAP / Singular.

Thanks Jeroen and Sebastian for the screenshots!

**Comment by nthiery** [comment]
Crude preliminary report pushed. Anything to be put there besides the screenshots and the above issue description?

**Comment by jdemeyer** [comment]
What is missing here is actual packaging of the GAP and Singular kernels and uploading them to PyPI. See https://packaging.python.org/distributing/ for general information on packaging and distributing Python projects.

@sebasguts and @markuspf: can you do that or do you need help?

**Comment by bpilorget** [comment]
# Deliverables update
@minrk As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by nthiery** [comment]
Just a crossref since we discussed the topic earlier:  dynamic loading with libgap currently does not work at this stage because we compile libgap in Sage with all c functions prefixed to avoid potential name conflicts. There is a preliminary branch by Volker to remove this prefixing and thus reenable dynamic loading in libgap: https://trac.sagemath.org/ticket/19915

**Comment by nthiery** [comment]
Hi @sebasguts, @markuspf, @jdemeyer,

We will all be attending the Jupyter workshop in two weeks from now. Shall we use the occasion to have a quick sprint together and finalize this ticket? All that remains to do is the pip/sage packaging. Sitting side by side, this should be a breeze.

**Comment by jdemeyer** [comment]
+1

Note that I will arrive Tuesday evening in Edinburgh.

**Comment by sebasguts** [comment]
Sounds good to me. I will be there the whole week, so plenty of time.

**Comment by dimpase** [comment]
I will be there only for Thursday and Friday, as I must attend to visitors in Oxford.

**Comment by jdemeyer** [comment]
I just volunteered to lead this deliverable.

**Comment by markuspf** [comment]
The GAP jupyter kernel is now available as a pip package: https://pypi.python.org/pypi/jupyter_gap_wrapper/0.8 (though I am still fiddling with the release process, in particular I'd like to synchronise the sources available from github and from pypi). Also note that I am more actively working on a standalone version using GAP itself (no python in between).

**Comment by markuspf** [comment]
Right, I renamed the package to `jupyter-kernel-gap` to be in line with `jupyter-kernel-singular`: https://pypi.python.org/pypi/jupyter-kernel-gap and I polished it a little bit.

I will get @mcmartins to integrate the syntax highlighting we have into it too (today).

**Comment by sebasguts** [comment]
So, even if everything is already checked in the boxes above, I will give a quick summary on the jupyter kernel for Singular:
* Kernel is available on PyPI as jupyter_kernel_singular
* Kernel is integrated into SageMathCloud
* Fully functional interface to Singular
* Either interacts directly with the Singular interpreter from Python via the PySingular Python module, available on PyPI, or
  with the REPL via pexpect.
* IPyWidgets can be used for interactions
* Images can be created using surf, an external program, and Singular's plot_jupyter.lib
* [Example Notebook](https://github.com/sebasguts/jupyter-singular/blob/master/Demo.ipynb)
* [Detailed installation instructions](https://www.singular.uni-kl.de/index.php/graphical-interface.html)
* [Direct link to screenshot](https://www.singular.uni-kl.de/Images/screenshot_jupyter.jpg)

**Comment by nthiery** [comment]
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by minrk** [comment]
@nthiery my understanding is that this report is all complete as of November. Is there anything more to do?

**Comment by nthiery** [comment]
Hi @minrk,
For the report itself, all that remains to do is fetching the latest github issue description and adding a screenshot for the GAP interface (it currently is a copy of the screenshot for Singular).
Other than this, the more of the remaining items we can tick in the issue description, the better. @jdemeyer?

**Comment by jdemeyer** [comment]
I'll have a look at this on monday.

**Comment by jdemeyer** [comment]
@markuspf : could you provide an example notebook which shows a simple GAP computation? I know essentially nothing of GAP, so it's best if somebody else does that.

**Comment by jdemeyer** [comment]
What exactly does "SageMathCloud integration" mean?

**Comment by nthiery** [comment]
Hi Jeroen,

>    What exactly does "SageMathCloud integration" mean?

Just that the jupyter-XXX kernel is installed on cloud.sagemath.org,
so that a user can choose XXX as kernel when running Jupyter notebooks
there.

Cheers,
		Nicolas

**Comment by jdemeyer** [comment]
I just sent a request to help@sagemath.com for the GAP and PARI/GP Jupyter kernels.

The report is updated with examples of all 4 kernels (thanks to @dimpase for the GAP example).

Note that some Sage tickets are still in needs_review, I hope that is not a problem.

**Comment by nthiery** [comment]
>    Note that some Sage tickets are still in needs_review, I hope
>    that is not a problem.

That's fair enough. They are non controversial; as long as we keep
pushing them, they will get in soon, maybe even before the reviewers
read the report.

Thanks for all the work!

**Comment by jdemeyer** [comment]
> They are non controversial

Well, the PARI one might be because I'm adding lots of patches to PARI which are not (yet?) accepted by upstream.

**Comment by nthiery** [comment]
I just proofread the issue description and report. I made some minor edits (larger screenshots, markdown syntax fixes to not confuse pandoc, fixed our Makefile so that trac references would not get messed up). I believe it's good to go, up to the tick boxes for the SMC integration. Please ping me if there is progress there, and I'll then submit. Otherwise, I'll wait until Monday and submit as is.

Cheers,

**Comment by jdemeyer** [comment]
I made some minor edits to the GitHub issue description. If you regenerate the corresponding TeX, you can submit.

**Comment by jdemeyer** [comment]
I just noticed now that the Sage ticket for the GAP kernel still needs review: https://trac.sagemath.org/ticket/21416

If you didn't know what to do on thursday, please review this ticket!

**Comment by slel** [comment]
Regarding CoCalc (formerly SageMathCloud) integration of Jupyter kernels:
- Singular: tested at ODK workshop at ICMS, live in CoCalc since late January 2017
- GAP: tested at Sage Days 87, live in CoCalc since late July 2017
- PARI: tested at Sage Days 87, live in CoCalc since late July 2017
