### ISSUE TITLE
D4.7: Full featured Jupyter interface for GAP, PARI/GP, Singular

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#96]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other
- **Task:** T4.1 (#69)
- **Proposal:** [p. 47](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.7/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.7/))

For the basic Jupyter interface, see #93.
- GAP: http://gap-packages.github.io/JupyterKernel
  - [ ] support complete_request (tab completion)
  - [ ] support inspect_request (shift-tab in notebook)
  - [ ] provide some rich display of objects and/or plotting, as appropriate
  - [ ] reasonably well documented, installable, etc.
  - [x] distributed with SageMath: https://trac.sagemath.org/ticket/21416
  - [x] installed on CoCalc: https://github.com/sagemathinc/cocalc/issues/1706
- PARI: https://github.com/jdemeyer/pari_jupyter
  - [x] support complete_request (tab completion)
  - [x] support inspect_request (shift-tab in notebook)
  - [x] provide some rich display of objects and/or plotting, as appropriate
  - [x] reasonably well documented, installable, etc.
  - [x] distributed with SageMath: https://trac.sagemath.org/ticket/19372
  - [x] installed on CoCalc: https://github.com/sagemathinc/cocalc/issues/160
- Singular: https://github.com/sebasguts/jupyter_kernel_singular
  - [x] support complete_request (tab completion)
  - [ ] support inspect_request (shift-tab in notebook)
  - [x] provide some rich display of objects and/or plotting, as appropriate
  - [x] reasonably well documented, installable, etc.
  - [x] distributed with SageMath: https://trac.sagemath.org/ticket/22378
  - [x] installed on CoCalc: https://github.com/sagemathinc/cocalc/issues/1553
- xeus-cling (C++)
  - [x] installs on CoCalc as a user: https://share.cocalc.com/share/4711033a-b5d8-4fb3-9708-e9019ba1c158/Install-xeus-cling-in-CoCalc-project.md?viewer=share
  - [ ] installed on CoCalc system-wide: https://github.com/sagemathinc/cocalc/issues/2324
- [MMT](https://www.kwarc.info/systems/mmt/); see #85.
  - [x] widgets
- [ ] Syntax highlighting: #175

**Comment by defeo** [comment]
[Trac ticket 20589](http://trac.sagemath.org/ticket/20589) relates to this.

**Comment by minrk** [comment]
Month 14 as the due date for this deliverable is a typo in the proposal, and should be Month 24. This should be formally updated to M24 (@nthiery).

**Comment by jdemeyer** [comment]
> Month 14 as the due date for this deliverable is a typo in the proposal, and should be Month 24. This should be formally updated to M24 (@nthiery).

ping (Nicolas?)

**Comment by bpilorget** [comment]
Ah yes... Well we will ask the Project Officer to take that into account. If Michael really does change partner we will need to to another amendment anyway...

**Comment by jdemeyer** [comment]
What should be done here? Of course 'full featured' is very ambiguous. The only thing I can immediately think of is syntax highlighting. But I know essentially nothing about Javascript, so I don't think it's a good idea for me to work on that.

**Comment by minrk** [comment]
I would say a full-featured Jupyter kernel means:

- [ ] syntax highlighting
- [ ] supports complete_request (tab completion)
- [ ] supports inspect_request (shift-tab in notebook)
- [ ] provides some rich display of objects and/or plotting, as appropriate
- [ ] is reasonably well documented, installable, etc.

omitting (with reason) any individual item, as appropriate.

**Comment by minrk** [comment]
I think the gist is: D4.4's goal is to show that it's possible and get the basics going, and D4.7 was to develop it the level of being useful, which is dependent on the expectations of the user community of each kernel. Based on the deliverable consolidation discussion, these probably shouldn't have been separate deliverables and I would merge them into "Jupyter kernels for GAP, PARI/GP, Singular" if D4.4 weren't already delivered.

**Comment by nthiery** [comment]
>    I would say a full-featured Jupyter kernel means:
>      * [ ] syntax highlighting
>      * [ ] supports complete_request (tab completion)
>      * [ ] supports inspect_request (shift-tab in notebook)
>      * [ ] provides some rich display of objects and/or plotting, as
>        appropriate
>      * [ ] is reasonably well documented, installable, etc.
> 
>    omitting (with reason) any individual item, as appropriate.

+1

I would add: distribution of the kernel with Sage (preferably as a
standard package) and installation on CoCalc (possibly as a side
effect of the former). It could be reasonable for the kernel to be
included as well in the distribution of the relevant component itself.

Possibly also some of the items at the end of the description of:

        https://github.com/OpenDreamKit/OpenDreamKit/issues/94

@jdemeyer: which of the above would be willing to handle? For the
others (plausibly those requiring javascript work) we will need to
find someone!

Cheers,
		Nicolas

**Comment by videlec** [comment]
> For the others (plausibly those requiring javascript work) we will need to find someone!

Vincent K (engineer at Bordeaux) is mostly done with the gmpy2 and pplpy integration in Sage. That might be a good continuation! I will ask him about working on the Pari kernel (starting with fixing [issue 2](https://github.com/jdemeyer/pari_jupyter/issues/2) and [issue 3](https://github.com/jdemeyer/pari_jupyter/issues/3)). And possibly more kernels after that. Is that ok?

**Comment by embray** [comment]
I can help with all of the above if needed, though I know virtually nothing about GAP, PARI/GP, etc. beyond some basics of how they work. So if there are people with specific knowledge of what features would be useful in kernels for them (as in, the ones @minrk listed) I can work with them on the implementation.

**Comment by sebasguts** [comment]
Short update on the Singular kernel: Tab-completion is available, as well as documentation. I will give an update of the remaining points during this week.

**Comment by bpilorget** [comment]
@minrk @jdemeyer  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by sebasguts** [comment]
`inspect_request` will be possible in the Singular kernel in the near future. I am not sure I can make it until end of August, but I will try. Syntax-Highlighting might work until then, too.

There is the possibility to plot images, using surf. Does this count as rich output?

**Comment by nthiery** [comment]
Dear Jupyter kernel writers,

Of course it's always good to look over each other shoulders for
inspiration of what could be useful features. Yet each component
(GAP/Singular/...) is different in its use cases. Rather than trying
to tick boxes from a uniform list of should-have features, let's use
this deliverable as an occasion to look at the feedback from users of
each basic kernel, and devote some time to implement the most
requested features. If this requires a couple more weeks, that's ok.

By the way: it would be good to include in the report some
quantitative and/or qualitative metrics of actual use of each kernel.
Example of good qualitative metric: a brief mention of Wolfram's use
of Jupyter for teaching Singular at AIMS, with a link to a blog post
on the topic.

**Comment by jdemeyer** [comment]
> let's use this deliverable as an occasion to look at the feedback from users of each basic kernel

I'm sorry to say this, but I do not know anybody actually using one of these kernels.

**Comment by jdemeyer** [comment]
> There is the possibility to plot images, using surf

Well, modulo the installation issues regarding `surf`. For example, it was refused as optional Sage package because it is too hard to build on OS X.

The problem is that surf-in-Jupyter only needs a small subset of the full `surf` program, and it's precisely the parts which are **not** needed for Jupyter that contribute to the build difficulties.

Anyway, I don't know how relevant this is to this deliverable, but I thought that it should be mentioned.

**Comment by sebasguts** [comment]
> I'm sorry to say this, but I do not know anybody actually using one of these kernels.

There are people using the Singular kernel. I don't know any of those, either, but I received some request for bug fixes, mostly from students, and I also was pointed to this example https://github.com/jifarran/brnoeth/blob/master/brnoeth.ipynb of somebody using it to publish his talk. But I am not sure how to benefit from their experiences, so I think your claim is valid here.

> Well, modulo the installation issues regarding `surf`. 

True, but `Singular` itself relies on `sur`f for its images, so there is probably no way around it except including the relevant parts of `surf` either in `Singular` or in the `Singular` kernel. I am not sure if this is really the way to go. Optional features of `Singular` depend on other software, which is also not bundled with `Singular`. So to say, if you don't have `polymake` installed on your computer, you cannot use some `Singular` features in the Jupyter kernel either.

**Comment by slel** [comment]
I edited the issue description to add the items suggested by @minrk and @nthiery
in their comments https://github.com/OpenDreamKit/OpenDreamKit/issues/96#issuecomment-315376165 and https://github.com/OpenDreamKit/OpenDreamKit/issues/96#issuecomment-315474684.

I ticked boxes and added links to relevant SageMath trac tickets or CoCalc github issues,
please tick more boxes and add more links if relevant.

Some work on the CoCalc installs was carried out at the following two events:
- OpenDreamKit workshop on computational mathematics with Jupyter,
  Edinburgh, Scotland, UK, January 2017 [0]
- Sage Days 87, Burlington, Vermont, USA, July 2017 [1].

[0] http://opendreamkit.org/2017/01/16/Computational_Mathematics_with_Jupyter/
[1] https://wiki.sagemath.org/days87

Regarding usage, I started advertising the availability on CoCalc, and also got some
spontaneous questions about using GAP in Jupyter notebooks on CoCalc at a meeting
on Braid groups and rational maps earlier this week in Harvard.

CoCalc has an issue about adding mocha tests for gap and pari/gp juypter kernels: https://github.com/sagemathinc/cocalc/issues/2243

A CoCalc blog post about the availability in CoCalc of these new Jupyter kernels is in preparation.

**Comment by vinklein** [comment]
We have a working syntax highliting for PARI/GP. [/pari_jupyter PR#5](https://github.com/jdemeyer/pari_jupyter/pull/5). I am currently working on singular kernel highlight.

**Comment by sebasguts** [comment]
@vinklein That it phantastic. If I can help you with any resources or if you need any change in PySingular or the singular jupyter kernel, let me know.

**Comment by nthiery** [comment]
On Fri, Nov 24, 2017 at 02:41:40PM +0000, vinklein wrote:
>    We have a working syntax highliting for PARI/GP. [1]/pari_jupyter PR#5.
>    I am currently working on singular kernel highlight.

Oh, nice!!!

**Comment by nthiery** [comment]
Hi,
With @sebasguts and @jdemeyer, we used the occasion of being in the same room to start drafting the report for this deliverable. It's was due in August, our kernels are in quite a good state (better is always possible). So let's get this done soon and move on.

Since we were editing all at the same time, we use the following pad:

    https://www.lri.fr/etherpad/p/odk-jupyter-kernel-report

Please hack in. Especially those who contributed to the kernels: @markuspf, @vinklein: proofread, extend, ...

When things will have stabilized, @jdemeyer will move the text into our git repo.

@alex-konovalov, @markuspf: if relevant, please extend the Teaching section with uses of the GAP kernel  in CoDima/... e.g. for teaching.

@gouarin: please have a brief look at the Implementation and Teaching section, and add an itemized list of features in the first comment of this issue.

@jdemeyer: please go through this ticket, and harvest any relevant piece of data.

@florian-rabe: there now is an mmt kernel, right? could you insert some words about it in the pad, and add an itemized list of features in the first comment of this issue description?

Thanks everyone!

**Comment by jdemeyer** [comment]
I just copied the pad to https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.7/report.tex so please don't edit the pad anymore...

**Comment by jdemeyer** [comment]
On the pad at the end, there is
```
\section{Detailed list of features}

TODO at the end: include here the itemized check list from the github description.
```

Are we sure that we want to do that? I don't really see the point.

**Comment by jdemeyer** [comment]
Should we really have a section about the SageMath kernel implementation in this report? I thought this deliverable was about other kernels, while D4.5 (#94) was about the SageMath kernel.

**Comment by nthiery** [comment]
>    Should we really have a section about the SageMath kernel
>    implementation in this report? I thought this deliverable was about
>    other kernels, while D4.5 ([1]#94) was about the SageMath kernel.

Good question. Please have a look at the D4.5 report. If we did not
describe there in some detail the implementation of the SageMath
kernel, then this report would be a natural place to do it. Otherwise
I believe it still would be good to say a few words: this report is a
good occasion to give an horizon tour of approaches to implement
kernels for math software.

**Comment by nthiery** [comment]
>    On the pad at the end, there is
> \section{Detailed list of features}
> 
> TODO at the end: include here the itemized check list from the github descriptio
> n.
> 
>    Are we sure that we want to do that? I don't really see the point.

Well, it will be cheap to do anyaway (just copying in the
github_issue_description.tex that will be produced automatically). So
I believe we might as well include it: it contains useful information
for someone that would want to dig in or know more in details the
status of each kernel. Or do you see some inconvenient?

**Comment by jdemeyer** [comment]
> Well, it will be cheap to do anyaway

Just saying that it's cheap to do shouldn't be sufficient reason to include it.

Allow me to paste one of my favourite quotes (from Antoine de Saint Exupéry):

    Il semble que la perfection soit atteinte non quand il n'y a plus rien à ajouter,
    mais quand il n'y a plus rien à retrancher.

**Comment by nthiery** [comment]
>    Just saying that it's cheap to do shouldn't be sufficient reason to
>    include it.

Certainly. But my whole argument is "it includes useful information,
at no additional cost".

**Comment by sebasguts** [comment]
@jdemeyer Thanks. I added a new singular screen cap with syntax highlight and the full surfer image. Will do a proofread and singular thebelab until the end of next week.

**Comment by jdemeyer** [comment]
Somebody added xeus-cling on this page, but can we really consider that as part of ODK?

**Comment by slel** [comment]
I think it's ok, especially since

- Loïc Gouarin is part of the team behind xeus-cling, and conceivably
  devoted part of his OpenDreamKit funding to work on xeus-cling.

- I used OpenDreamKit funded time to work on integration in CoCalc.

**Comment by jdemeyer** [comment]
I just pushed a major update to the report. Should I add the generated PDF also in the git repo? I don't remember how this is supposed to work.

At the XFEL meeting, somebody mentioned the MMT kernel https://github.com/UniFormal/mmt_jupyter_kernel

I really don't know much about MMT or its user interface, so I don't think that I could write something about it.

**Comment by nthiery** [comment]
Thanks Jeroen! Don't worry about the PDF; we will add it at the last minute.

@florian-rabe: would you get a chance to write a few paragraphs describing the MMT kernel?

**Comment by florian-rabe** [comment]
You can copy-paste from https://github.com/KWARC/OpenDreamKit/tree/master/WP4/D4.11
I wrote that this week.

**Comment by jdemeyer** [comment]
Nicolas, you mentioned that I should add widgets but this is already covered by D4.5. It seems strange to me to add that feature to two deliverables, especially in the same reporting period.

**Comment by nthiery** [comment]
>    Nicolas, you mentioned that I should add widgets but this is already
>    covered by D4.5. It seems strange to me to add that feature to two
>    deliverables, especially in the same reporting period.

Ah, right, good point. Nevertheless, it's still worthwhile mentioning
with a cross-reference "implemented as part of D4.5", to give a bit of
the big picture to the reader.

Btw: on https://github.com/OpenDreamKit/OpenDreamKit/issues/94 the
item for interacts/widgets is not checked; any reason? Otherwise go
ahead an check it.

**Comment by nthiery** [comment]
I added a brief section about MMT (@florian-rabe: you may want to double-check), and double checked that the work was widgets work was indeed referenced as implemented as part of D4.5.
@jdemeyer: do you see anything else you'd like to change, or shall I submit the report as is?

**Comment by florian-rabe** [comment]
I made minor changes to the MMT paragraph. OK otherwise.

**Comment by nthiery** [comment]
Thanks @florian-rabe!
@jdmeyer: should I submit the report as is?

**Comment by jdemeyer** [comment]
I thought you wanted me to add something about widgets.

**Comment by nthiery** [comment]
Yeah; in the mean time, I realized that it was already there in Section 4.7; sorry for that noise:
```
- ...
- Improvements to Jupyter’s widgets and interact functionality to be as feature rich as in
the old Sage Notebook.
The last item was implemented by Jeroen Demeyer under OpenDreamKit funding as part of
D4.5: “Sage notebook / JUPYTER notebook convergence”.
```
Unless of course you see something more specific to say!

**Comment by alex-konovalov** [comment]
I've a collection of the some GAP Jupyter notebooks at https://github.com/alex-konovalov/gap-teaching/ which I used at the GAP tutorial at [PGTC 2018](http://www-groups.mcs.st-and.ac.uk/~pgtc2018/). One could also run on binder. Is this interesting for this report?

**Comment by nthiery** [comment]
>    I've a collection of the some GAP Jupyter notebooks at
>    [1]https://github.com/alex-konovalov/gap-teaching/ which I used at the
>    GAP tutorial at [2]PGTC 2018. One could also run on binder. Is this
>    interesting for this report?

Thanks for the suggestion Alex! Could you add a few lines about it around:

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.7/report.tex#L111

We should also have a use case around authoring interactive course
notes on our web page, with links to instances including the above:

        https://opendreamkit.org/tag/use-case

Volunteers welcome :-)

**Comment by slel** [comment]
For greater visibility, it would make sense to add binder-enabled examples
of using the GAP, MMT, PARI/GP, SageMath, Singular kernels for Jupyter at
https://github.com/jupyter/jupyter.github.io/blob/master/_data/try.yml
so they can appear at
http://jupyter.org/try

**Comment by slel** [comment]
Making everything conda-installable from the conda-forge channel
would also facilitate adoption.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
